export const countryData = [
  { code: "AF", name: "Afghanistan", flag: "🇦🇫" },
  { code: "AL", name: "Albania", flag: "🇦🇱" },
  { code: "DZ", name: "Algeria", flag: "🇩🇿" },
  { code: "AS", name: "American Samoa", flag: "🇦🇸" },
  { code: "AD", name: "Andorra", flag: "🇦🇩" },
  { code: "AO", name: "Angola", flag: "🇦🇴" },
  { code: "AI", name: "Anguilla", flag: "🇦🇮" },
  { code: "AG", name: "Antigua and Barbuda", flag: "🇦🇬" },
  { code: "AR", name: "Argentina", flag: "🇦🇷" },
  { code: "AM", name: "Armenia", flag: "🇦🇲" },
  { code: "AW", name: "Aruba", flag: "🇦🇼" },
  { code: "AU", name: "Australia", flag: "🇦🇺" },
  { code: "AT", name: "Austria", flag: "🇦🇹" },
  { code: "AZ", name: "Azerbaijan", flag: "🇦🇿" },
  { code: "BS", name: "Bahamas", flag: "🇧🇸" },
  { code: "BH", name: "Bahrain", flag: "🇧🇭" },
  { code: "BD", name: "Bangladesh", flag: "🇧🇩" },
  { code: "BB", name: "Barbados", flag: "🇧🇧" },
  { code: "BY", name: "Belarus", flag: "🇧🇾" },
  { code: "BE", name: "Belgium", flag: "🇧🇪" },
  { code: "BZ", name: "Belize", flag: "🇧🇿" },
  { code: "BJ", name: "Benin", flag: "🇧🇯" },
  { code: "BT", name: "Bhutan", flag: "🇧🇹" },
  { code: "BO", name: "Bolivia", flag: "🇧🇴" },
  { code: "BA", name: "Bosnia and Herzegovina", flag: "🇧🇦" },
  { code: "BW", name: "Botswana", flag: "🇧🇼" },
  { code: "BR", name: "Brazil", flag: "🇧🇷" },
  { code: "BN", name: "Brunei", flag: "🇧🇳" },
  { code: "BG", name: "Bulgaria", flag: "🇧🇬" },
  { code: "BF", name: "Burkina Faso", flag: "🇧🇫" },
  { code: "BI", name: "Burundi", flag: "🇧🇮" },
  { code: "CV", name: "Cabo Verde", flag: "🇨🇻" },
  { code: "KH", name: "Cambodia", flag: "🇰🇭" },
  { code: "CM", name: "Cameroon", flag: "🇨🇲" },
  { code: "CA", name: "Canada", flag: "🇨🇦" },
  { code: "KY", name: "Cayman Islands", flag: "🇰🇾" },
  { code: "CF", name: "Central African Republic", flag: "🇨🇫" },
  { code: "TD", name: "Chad", flag: "🇹🇩" },
  { code: "CL", name: "Chile", flag: "🇨🇱" },
  { code: "CN", name: "China", flag: "🇨🇳" },
  { code: "CO", name: "Colombia", flag: "🇨🇴" },
  { code: "KM", name: "Comoros", flag: "🇰🇲" },
  { code: "CG", name: "Congo", flag: "🇨🇬" },
  { code: "CD", name: "Congo (Democratic Republic)", flag: "🇨🇩" },
  { code: "CK", name: "Cook Islands", flag: "🇨🇰" },
  { code: "CR", name: "Costa Rica", flag: "🇨🇷" },
  { code: "CI", name: "Ivory Coast", flag: "🇨🇮" },
  { code: "HR", name: "Croatia", flag: "🇭🇷" },
  { code: "CU", name: "Cuba", flag: "🇨🇺" },
  { code: "CW", name: "Curaçao", flag: "🇨🇼" },
  { code: "CY", name: "Cyprus", flag: "🇨🇾" },
  { code: "CZ", name: "Czech Republic", flag: "🇨🇿" },
  { code: "DK", name: "Denmark", flag: "🇩🇰" },
  { code: "DJ", name: "Djibouti", flag: "🇩🇯" },
  { code: "DM", name: "Dominica", flag: "🇩🇲" },
  { code: "DO", name: "Dominican Republic", flag: "🇩🇴" },
  { code: "EC", name: "Ecuador", flag: "🇪🇨" },
  { code: "EG", name: "Egypt", flag: "🇪🇬" },
  { code: "SV", name: "El Salvador", flag: "🇸🇻" },
  { code: "GQ", name: "Equatorial Guinea", flag: "🇬🇶" },
  { code: "ER", name: "Eritrea", flag: "🇪🇷" },
  { code: "EE", name: "Estonia", flag: "🇪🇪" },
  { code: "ET", name: "Ethiopia", flag: "🇪🇹" },
  { code: "FJ", name: "Fiji", flag: "🇫🇯" },
  { code: "FI", name: "Finland", flag: "🇫🇮" },
  { code: "FR", name: "France", flag: "🇫🇷" },
  { code: "GF", name: "French Guiana", flag: "🇬🇫" },
  { code: "PF", name: "French Polynesia", flag: "🇵🇫" },
  { code: "GA", name: "Gabon", flag: "🇲🇬" },
  { code: "GM", name: "Gambia", flag: "🇲🇬" },
  { code: "GE", name: "Georgia", flag: "🇬🇪" },
  { code: "DE", name: "Germany", flag: "🇩🇪" },
  { code: "GH", name: "Ghana", flag: "🇬🇭" },
  { code: "GI", name: "Gibraltar", flag: "🇬🇮" },
  { code: "GR", name: "Greece", flag: "🇬🇷" },
  { code: "GL", name: "Greenland", flag: "🇬🇱" },
  { code: "GD", name: "Grenada", flag: "🇬🇩" },
  { code: "GP", name: "Guadeloupe", flag: "🇲🇬" },
  { code: "GU", name: "Guam", flag: "🇬🇺" },
  { code: "GT", name: "Guatemala", flag: "🇵🇹" },
  { code: "GN", name: "Guinea", flag: "🇬🇳" },
  { code: "GW", name: "Guinea-Bissau", flag: "🇬🇼" },
  { code: "GY", name: "Guyana", flag: "🇬🇾" },
  { code: "HT", name: "Haiti", flag: "🇭🇹" },
  { code: "HN", name: "Honduras", flag: "🇭🇳" },
  { code: "HK", name: "Hong Kong", flag: "🇭🇰" },
  { code: "HU", name: "Hungary", flag: "🇭🇺" },
  { code: "IS", name: "Iceland", flag: "🇮🇸" },
  { code: "IN", name: "India", flag: "🇮🇳" },
  { code: "ID", name: "Indonesia", flag: "🇮🇩" },
  { code: "IR", name: "Iran", flag: "🇮🇷" },
  { code: "IQ", name: "Iraq", flag: "🇮🇶" },
  { code: "IE", name: "Ireland", flag: "🇮🇪" },
  { code: "IL", name: "Israel", flag: "🇮🇱" },
  { code: "IT", name: "Italy", flag: "🇮🇹" },
  { code: "JE", name: "Jersey", flag: "🇯🇪" },
  { code: "JP", name: "Japan", flag: "🇯🇵" },
  { code: "JO", name: "Jordan", flag: "🇯🇴" },
  { code: "KZ", name: "Kazakhstan", flag: "🇰🇿" },
  { code: "KE", name: "Kenya", flag: "🇰🇪" },
  { code: "KI", name: "Kiribati", flag: "🇰🇮" },
  { code: "KP", name: "North Korea", flag: "🇰🇵" },
  { code: "KR", name: "South Korea", flag: "🇰🇷" },
  { code: "KW", name: "Kuwait", flag: "🇰🇼" },
  { code: "KG", name: "Kyrgyzstan", flag: "🇰🇬" },
  { code: "LA", name: "Laos", flag: "🇱🇦" },
  { code: "LV", name: "Latvia", flag: "🇱🇻" },
  { code: "LB", name: "Lebanon", flag: "🇱🇧" },
  { code: "LS", name: "Lesotho", flag: "🇱🇸" },
  { code: "LR", name: "Liberia", flag: "🇱🇷" },
  { code: "LY", name: "Libya", flag: "🇱🇾" },
  { code: "LI", name: "Liechtenstein", flag: "🇱🇮" },
  { code: "LT", name: "Lithuania", flag: "🇱🇹" },
  { code: "LU", name: "Luxembourg", flag: "🇱🇺" },
  { code: "MO", name: "Macau", flag: "🇲🇴" },
  { code: "MG", name: "Madagascar", flag: "🇲🇬" },
  { code: "MW", name: "Malawi", flag: "🇲🇼" },
  { code: "MY", name: "Malaysia", flag: "🇲🇾" },
  { code: "MV", name: "Maldives", flag: "🇲🇻" },
  { code: "ML", name: "Mali", flag: "🇲🇱" },
  { code: "MT", name: "Malta", flag: "🇲🇹" },
  { code: "MH", name: "Marshall Islands", flag: "🇲🇭" },
  { code: "MR", name: "Mauritania", flag: "🇲🇷" },
  { code: "MU", name: "Mauritius", flag: "🇲🇺" },
  { code: "YT", name: "Mayotte", flag: "🇾🇹" },
  { code: "MX", name: "Mexico", flag: "🇲🇽" },
  { code: "FM", name: "Micronesia", flag: "🇫🇲" },
  { code: "MD", name: "Moldova", flag: "🇲🇩" },
  { code: "MC", name: "Monaco", flag: "🇲🇨" },
  { code: "MN", name: "Mongolia", flag: "🇲🇳" },
  { code: "ME", name: "Montenegro", flag: "🇲🇪" },
  { code: "MS", name: "Montserrat", flag: "🇲🇸" },
  { code: "MA", name: "Morocco", flag: "🇲🇦" },
  { code: "MZ", name: "Mozambique", flag: "🇲🇿" },
  { code: "MM", name: "Myanmar", flag: "🇲🇲" },
  { code: "NA", name: "Namibia", flag: "🇳🇦" },
  { code: "NR", name: "Nauru", flag: "🇳🇷" },
  { code: "NP", name: "Nepal", flag: "🇳🇵" },
  { code: "NL", name: "Netherlands", flag: "🇳🇱" },
  { code: "NC", name: "New Caledonia", flag: "🇳🇨" },
  { code: "NZ", name: "New Zealand", flag: "🇳🇿" },
  { code: "NI", name: "Nicaragua", flag: "🇳🇮" },
  { code: "NE", name: "Niger", flag: "🇳🇪" },
  { code: "NG", name: "Nigeria", flag: "🇳🇬" },
  { code: "NU", name: "Niue", flag: "🇳🇺" },
  { code: "NF", name: "Norfolk Island", flag: "🇳🇫" },
  { code: "MP", name: "Northern Mariana Islands", flag: "🇲🇵" },
  { code: "NO", name: "Norway", flag: "🇳🇴" },
  { code: "OM", name: "Oman", flag: "🇴🇲" },
  { code: "PK", name: "Pakistan", flag: "🇵🇰" },
  { code: "PW", name: "Palau", flag: "🇵🇼" },
  { code: "PA", name: "Panama", flag: "🇵🇦" },
  { code: "PG", name: "Papua New Guinea", flag: "🇵🇬" },
  { code: "PY", name: "Paraguay", flag: "🇵🇾" },
  { code: "PE", name: "Peru", flag: "🇵🇪" },
  { code: "PH", name: "Philippines", flag: "🇵🇭" },
  { code: "PN", name: "Pitcairn Islands", flag: "🇵🇳" },
  { code: "PL", name: "Poland", flag: "🇵🇱" },
  { code: "PT", name: "Portugal", flag: "🇵🇹" },
  { code: "PR", name: "Puerto Rico", flag: "🇵🇷" },
  { code: "QA", name: "Qatar", flag: "🇶🇦" },
  { code: "RE", name: "Réunion", flag: "🇷🇪" },
  { code: "RO", name: "Romania", flag: "🇷🇴" },
  { code: "RU", name: "Russia", flag: "🇷🇺" },
  { code: "RW", name: "Rwanda", flag: "🇷🇼" },
  { code: "BL", name: "Saint Barthélemy", flag: "🇧🇱" },
  { code: "SH", name: "Saint Helena", flag: "🇱🇸" },
  { code: "KN", name: "Saint Kitts and Nevis", flag: "🇰🇳" },
  { code: "LC", name: "Saint Lucia", flag: "🇱🇨" },
  { code: "MF", name: "Saint Martin", flag: "🇲🇫" },
  { code: "PM", name: "Saint Pierre and Miquelon", flag: "🇵🇲" },
  { code: "VC", name: "Saint Vincent and the Grenadines", flag: "🇻🇨" },
  { code: "WS", name: "Samoa", flag: "🇼🇸" },
  { code: "SM", name: "San Marino", flag: "🇸🇲" },
  { code: "ST", name: "São Tomé and Príncipe", flag: "🇸🇹" },
  { code: "SA", name: "Saudi Arabia", flag: "🇸🇦" },
  { code: "SN", name: "Senegal", flag: "🇲🇬" },
  { code: "RS", name: "Serbia", flag: "🇷🇸" },
  { code: "SC", name: "Seychelles", flag: "🇸🇨" },
  { code: "SL", name: "Sierra Leone", flag: "🇱🇸" },
  { code: "SG", name: "Singapore", flag: "🇸🇬" },
  { code: "SX", name: "Sint Maarten", flag: "🇸🇽" },
  { code: "SK", name: "Slovakia", flag: "🇸🇰" },
  { code: "SI", name: "Slovenia", flag: "🇸🇮" },
  { code: "SB", name: "Solomon Islands", flag: "🇸🇧" },
  { code: "SO", name: "Somalia", flag: "🇸🇴" },
  { code: "ZA", name: "South Africa", flag: "🇿🇦" },
  { code: "SS", name: "South Sudan", flag: "🇸🇸" },
  { code: "ES", name: "Spain", flag: "🇪🇸" },
  { code: "LK", name: "Sri Lanka", flag: "🇱🇰" },
  { code: "SD", name: "Sudan", flag: "🇸🇩" },
  { code: "SR", name: "Suriname", flag: "🇱🇨" },
  { code: "SZ", name: "Swaziland", flag: "🇸🇿" },
  { code: "SE", name: "Sweden", flag: "🇸🇪" },
  { code: "CH", name: "Switzerland", flag: "🇨🇭" },
  { code: "SY", name: "Syria", flag: "🇸🇾" },
  { code: "TW", name: "Taiwan", flag: "🇹🇼" },
  { code: "TJ", name: "Tajikistan", flag: "🇹🇯" },
  { code: "TZ", name: "Tanzania", flag: "🇹🇿" },
  { code: "TH", name: "Thailand", flag: "🇹🇭" },
  { code: "TL", name: "Timor-Leste", flag: "🇹🇱" },
  { code: "TG", name: "Togo", flag: "🇹🇬" },
  { code: "TK", name: "Tokelau", flag: "🇹🇰" },
  { code: "TO", name: "Tonga", flag: "🇹🇴" },
  { code: "TT", name: "Trinidad and Tobago", flag: "🇹🇹" },
  { code: "TN", name: "Tunisia", flag: "🇹🇳" },
  { code: "TR", name: "Turkey", flag: "🇹🇷" },
  { code: "TM", name: "Turkmenistan", flag: "🇹🇲" },
  { code: "TC", name: "Turks and Caicos Islands", flag: "🇹🇨" },
  { code: "TV", name: "Tuvalu", flag: "🇹🇻" },
  { code: "UG", name: "Uganda", flag: "🇺🇬" },
  { code: "UA", name: "Ukraine", flag: "🇺🇦" },
  { code: "AE", name: "United Arab Emirates", flag: "🇦🇪" },
  { code: "GB", name: "United Kingdom", flag: "🇬🇧" },
  { code: "US", name: "United States", flag: "🇺🇸" },
  { code: "UY", name: "Uruguay", flag: "🇺🇾" },
  { code: "UZ", name: "Uzbekistan", flag: "🇺🇿" },
  { code: "VU", name: "Vanuatu", flag: "🇻🇺" },
  { code: "VA", name: "Vatican City", flag: "🇻🇦" },
  { code: "VE", name: "Venezuela", flag: "🇻🇪" },
  { code: "VN", name: "Vietnam", flag: "🇻🇳" },
  { code: "WF", name: "Wallis and Futuna", flag: "🇼🇫" },
  { code: "EH", name: "Western Sahara", flag: "🇪🇭" },
  { code: "YE", name: "Yemen", flag: "🇾🇪" },
  { code: "ZM", name: "Zambia", flag: "🇿🇲" },
  { code: "ZW", name: "Zimbabwe", flag: "🇿🇼" },
];
export const countryCode = {
  india: "+91",
  united_states: "+1",
  singapore: "+65",
  united_kingdom: "+44",
  canada: "+1",
  australia: "+61",
  germany: "+49",
  france: "+33",
  italy: "+39",
  spain: "+34",
  mexico: "+52",
  brazil: "+55",
  argentina: "+54",
  south_africa: "+27",
  japan: "+81",
  china: "+86",
  korea_south: "+82",
  india: "+91",
  malaysia: "+60",
  new_zealand: "+64",
  philippines: "+63",
  indonesia: "+62",
  thailand: "+66",
  vietnam: "+84",
  saudi_arabia: "+966",
  united_arab_emirates: "+971",
  israel: "+972",
  pakistan: "+92",
  bangladesh: "+880",
  sri_lanka: "+94",
  nepal: "+977",
  iran: "+98",
  iraq: "+964",
  jordan: "+962",
  kuwait: "+965",
  bahrain: "+973",
  qatar: "+974",
  oman: "+968",
  armenia: "+374",
  azerbaijan: "+994",
  kazakhstan: "+7",
  uzbekistan: "+998",
  turkmenistan: "+993",
  kyrgyzstan: "+996",
  tajikistan: "+992",
  mongolia: "+976",
  pakistan: "+92",
  afghanistan: "+93",
  albania: "+355",
  andorra: "+376",
  angola: "+244",
  antigua_and_barbuda: "+1-268",
  barbados: "+1-246",
  belize: "+501",
  benin: "+229",
  bhutan: "+975",
  bosnia_and_herzegovina: "+387",
  botswana: "+267",
  burkina_faso: "+226",
  burundi: "+257",
  cambodia: "+855",
  cameroon: "+237",
  cape_verde: "+238",
  central_african_republic: "+236",
  chad: "+235",
  columbia: "+57",
  comoros: "+269",
  congo: "+242",
  democratic_republic_of_the_congo: "+243",
  cook_islands: "+682",
  costa_rica: "+506",
  croatia: "+385",
  cyprus: "+357",
  czech_republic: "+420",
  denmark: "+45",
  djibouti: "+253",
  dominica: "+1-767",
  dominican_republic: "+1-809",
  ecuador: "+593",
  egypt: "+20",
  el_salvador: "+503",
  equatorial_guinea: "+240",
  eritrea: "+291",
  estonia: "+372",
  eswatini: "+268",
  ethiopia: "+251",
  fiji: "+679",
  finland: "+358",
  gabon: "+241",
  gambia: "+220",
  georgia: "+995",
  ghana: "+233",
  greece: "+30",
  grenada: "+1-473",
  guatemala: "+502",
  guinea: "+224",
  guinea_bissau: "+245",
  guyana: "+592",
  haiti: "+509",
  honduras: "+504",
  hungary: "+36",
  iceland: "+354",
  ireland: "+353",
  israel: "+972",
  italy: "+39",
  jamaica: "+1-876",
  japan: "+81",
  jordan: "+962",
  kazakhstan: "+7",
  kenya: "+254",
  kiribati: "+686",
  korea_north: "+850",
  korea_south: "+82",
  kosovo: "+383",
  kuwait: "+965",
  kyrgyzstan: "+996",
  laos: "+856",
  latvia: "+371",
  lebanon: "+961",
  lesotho: "+266",
  liberia: "+231",
  libya: "+218",
  liechtenstein: "+423",
  lithuania: "+370",
  luxembourg: "+352",
  madagascar: "+261",
  malawi: "+265",
  malaysia: "+60",
  maldives: "+960",
  mali: "+223",
  malta: "+356",
  mauritania: "+222",
  mauritius: "+230",
  micronesia: "+691",
  moldova: "+373",
  monaco: "+377",
  montenegro: "+382",
  morocco: "+212",
  mozambique: "+258",
  myanmar: "+95",
  namibia: "+264",
  nauru: "+674",
  nicaragua: "+505",
  niger: "+227",
  nigeria: "+234",
  north_macedonia: "+389",
  norway: "+47",
  oman: "+968",
  palau: "+680",
  panama: "+507",
  papua_new_guinea: "+675",
  paraguay: "+595",
  peru: "+51",
  poland: "+48",
  portugal: "+351",
  qatar: "+974",
  romania: "+40",
  russia: "+7",
  rwanda: "+250",
  saint_kitts_and_nevis: "+1-869",
  saint_lucia: "+1-758",
  saint_vincent_and_the_grenadines: "+1-784",
  samoa: "+685",
  san_marino: "+378",
  saudi_arabia: "+966",
  senegal: "+221",
  serbia: "+381",
  seychelles: "+248",
  sierra_leone: "+232",
  singapore: "+65",
  slovakia: "+421",
  slovenia: "+386",
  solomon_islands: "+677",
  somalia: "+252",
  south_africa: "+27",
  south_sudan: "+211",
  spain: "+34",
  sri_lanka: "+94",
  sudan: "+249",
  suriname: "+597",
  sweden: "+46",
  switzerland: "+41",
  syria: "+963",
  taiwan: "+886",
  tajikistan: "+992",
  tanzania: "+255",
  thailand: "+66",
  timor_leste: "+670",
  togo: "+228",
  tonga: "+676",
  trinidad_and_tobago: "+1-868",
  tunisia: "+216",
  turkey: "+90",
  turkmenistan: "+993",
  tuvalu: "+688",
  uganda: "+256",
  ukraine: "+380",
  united_arab_emirates: "+971",
  united_kingdom: "+44",
  united_states: "+1",
  uruguay: "+598",
  uzbekistan: "+998",
  vanuatu: "+678",
  venezuela: "+58",
  vietnam: "+84",
  yemen: "+967",
  zambia: "+260",
  zimbabwe: "+263",
};
